name: Tests

on: [ push, pull_request ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3', '8.4']
    name: PHP ${{ matrix.php-versions }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP 
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        #extensions: memcached

    - name: Install Dependencies
      run: composer install

    - name: Tests
      run: make tests
